In this part, the decision trees are all simple, raw decision trees. They have not been improved. 

In [1]:
import numpy as np
from classification import *
from util import Util

## 3.1 train and test a raw decision tree on 3 datasets and test them

In [2]:
DecisionTreeClassifier.depth_limit = 100;
if __name__ == "__main__":
    print("Loading the training dataset...")
    # Change the dataset name here
    features, labels = Util.read_dataset("./data/train_full.txt")
    
    print("Training the decision tree...")
    classifier = DecisionTreeClassifier()
    node = classifier.fit(features, labels)

    features, y_test = Util.read_dataset("./data/test.txt")
    prediction = classifier.predict(features)

    print("accuracy:")
    accuracy = Evaluation.accuracy(y_test, prediction)
    print(accuracy)

    print("confusion_matrix:")
    confusion = Evaluation.confusion_matrix(y_test, prediction)
    print(confusion)

    print("recall:")
    (r, macro_r) = Evaluation.recall(y_test, prediction)
    print(r)
    print("average:")
    print(macro_r)

    print("precision:")
    (p, macro_p) = Evaluation.precision(y_test, prediction)
    print(p)
    print("average:")
    print(macro_p)

    print("f1_score:")
    (f1, macro_f1) = Evaluation.f1_score(y_test, prediction)
    print(f1)
    print("average:")
    print(macro_f1)

Loading the training dataset...
Training the decision tree...
accuracy:
0.865
confusion_matrix:
['A' 'C' 'E' 'G' 'O' 'Q']
[[33  0  0  1  0  0]
 [ 1 33  2  1  0  0]
 [ 0  0 24  0  1  1]
 [ 1  1  2 19  1  3]
 [ 0  2  0  1 27  4]
 [ 0  0  2  0  3 37]]
recall:
['A' 'C' 'E' 'G' 'O' 'Q']
[0.97058824 0.89189189 0.92307692 0.7037037  0.79411765 0.88095238]
average:
0.8607217969963067
precision:
['A' 'C' 'E' 'G' 'O' 'Q']
[0.94285714 0.91666667 0.8        0.86363636 0.84375    0.82222222]
average:
0.8648553992303992
f1_score:
['A' 'C' 'E' 'G' 'O' 'Q']
['A' 'C' 'E' 'G' 'O' 'Q']
[0.95652174 0.90410959 0.85714286 0.7755102  0.81818182 0.85057471]
average:
0.8603401533702528


## 3.2 cross validation using the raw decision tree 

In [3]:
features, labels = Util.read_dataset("./data/train_full.txt")
node_list, best_nodes = CrossValidation.cross_validation(features, labels, 10)

all accuracies in 10 cross validation:
[0.92564103 0.90512821 0.92564103 0.92307692 0.94615385 0.93846154
 0.8974359  0.93846154 0.91025641 0.92564103]
mean: 0.92
standard deviation: 0.01


## 3.3 raw decision trees now vote to predict

In [4]:
accuracies = np.zeros((10, ))
x_test, y_test = Util.read_dataset("./data/test.txt")
prediction_all = np.repeat(np.zeros_like(y_test).reshape(-1,y_test.size), 10, axis=0)
avg_acc = 0

for i in range(10):
    prediction = DecisionTreeClassifier(node_list[i]).predict(x_test)
    prediction_all[i,:] = prediction
    avg_acc += Evaluation.accuracy(prediction, y_test)/10
prediction_votes = np.zeros_like(y_test)

for i in range(y_test.size):
    votes = prediction_all[:,i]
    unique, counts = np.unique(votes, return_counts=True)
    prediction_votes[i] = unique[counts.argmax()]
    # optional: print all difference
    if (unique.size > 1):
        print(votes, end = " ")
        print("vote for: ", prediction_votes[i])
        
vote_accuracy = Evaluation.accuracy(prediction_votes, y_test)
print(f"vote accuracy of raw decision trees is {vote_accuracy:.4f}")

['Q' 'O' 'O' 'O' 'O' 'Q' 'O' 'O' 'Q' 'C'] vote for:  O
['C' 'E' 'E' 'E' 'E' 'C' 'E' 'C' 'E' 'E'] vote for:  E
['Q' 'O' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q'] vote for:  Q
['E' 'G' 'G' 'G' 'G' 'G' 'G' 'G' 'G' 'G'] vote for:  G
['G' 'G' 'E' 'G' 'G' 'G' 'Q' 'G' 'G' 'Q'] vote for:  G
['O' 'Q' 'O' 'Q' 'Q' 'O' 'O' 'O' 'Q' 'Q'] vote for:  O
['O' 'Q' 'O' 'Q' 'O' 'O' 'G' 'Q' 'G' 'O'] vote for:  O
['Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'G' 'Q' 'Q' 'Q'] vote for:  Q
['E' 'E' 'E' 'E' 'E' 'G' 'E' 'E' 'E' 'E'] vote for:  E
['Q' 'O' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q'] vote for:  Q
['Q' 'O' 'Q' 'Q' 'Q' 'G' 'Q' 'Q' 'Q' 'Q'] vote for:  Q
['A' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'C' 'C'] vote for:  C
['Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'Q' 'O' 'Q' 'Q'] vote for:  Q
['O' 'Q' 'Q' 'Q' 'O' 'O' 'O' 'G' 'Q' 'O'] vote for:  O
['G' 'G' 'G' 'G' 'G' 'G' 'E' 'G' 'G' 'Q'] vote for:  G
['G' 'O' 'E' 'E' 'O' 'Q' 'G' 'C' 'G' 'O'] vote for:  G
['G' 'A' 'G' 'A' 'O' 'G' 'A' 'A' 'A' 'O'] vote for:  A
['E' 'E' 'E' 'E' 'E' 'G' 'E' 'E' 'E' 'E'] vote for:  E
['A' 'C' '